forms/basicforms/basicapp/urls.py
from django.conf.urls import url
from basicapp import views #can also use from . import views

#template tagging
app_name = 'basic_app'
urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login')
]

forms/basicforms/basicforms/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from basicapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^formpage/',views.form_name_view,name='form_name'),
    url(r'^basicapp/',include('basicapp.urls')),
    url(r'^logout/$',views.user_logout,name='logout')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

forms/basicforms/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

forms/basicforms/basicapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

#custome validation
def check_for_z(value):
    if value[0].lower()!='z':
        raise forms.ValidationError("Name Needs to start with Z")

class FormName(forms.Form):
    name=forms.CharField(validators=[check_for_z])#custom validators
    email=forms.EmailField()
    verify_email = forms.EmailField(label="Enter Your Email Again")
    text=forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
    validators=[validators.MaxLengthValidator(0)]) #in-built validators

    def clean(self):
        all_clean_data = super().clean() #clean data on forms
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("Make sure that the emails MATCH!")

'''
    #validation

    def clean_botcatcher(self):
        botcatcher=self.cleaned_data['botcatcher']
        if len(botcatcher)>0:
            raise forms.ValidationError("GOTCHA BOT!")
        return botcatcher
'''

forms/basicforms/basicapp/views.py
from django.shortcuts import render
from . import forms
from basicapp.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    context_dict = {'text': 'hello world','number':100}
    return render(request, 'basicapp/index.html',context_dict)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'basicapp/registration.html',
    {'user_form': user_form,
    'profile_form': profile_form,
    'registered': registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failde!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("INVALID LOGIN DETAILS SUPPLIED!")
    else:
        return render(request,'basicapp/login.html',{})

def form_name_view(request):
    form=forms.FormName()

    if request.method=='POST':
        form=forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!")
            print("Name: "+form.cleaned_data['name'])
            print("Email: "+form.cleaned_data['email'])
            print("Text: "+form.cleaned_data['text'])

    return render(request,'basicapp/form_page.html',{'form':form})

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

forms/basicforms/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a href="{% url 'index' %}" class="navbar-brand">BRAND</a>
           </li>
           <li> <a href="{% url 'admin:index' %}" class="navbar-link">Admin</a> </li>
           <li> <a href="{% url 'basic_app:register' %}" class="navbar-link">Register</a> </li>
           <li> <a href="{% url 'basic_app:other' %}" class="navbar-link">Other</a> </li>
           {% if user.is_authenticated %}
             <li> <a href="{% url 'logout' %}" class="navbar-link">Logout</a></li>
            {% else %}
              <li> <a href="{% url 'basic_app:user_login' %}" class="navbar-link">Login</a> </li>
            {% endif %}  
        </ul>
      </div>
    </nav>

    <div class="container">
          {% block body_block %}
          <!-- Anything outside of this will be extended if inherited -->
          {% endblock %}
    </div>
  </body>
</html>

forms/basicforms/templates/basicapp/form_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <h1>Fill out the form</h1>
    <div class="container">
      <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

forms/basicforms/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
 {% block body_block %}
      <div class="jumbotron">
        <h1>Welcome to homepage!</h1>
        <h2>Go to /formpage to fill out the form</h2>
        <h3>{{ text|cut:'world' }}</h3>
        <h3>{{ number|add:"99" }}</h3>
    </div>
{% endblock %}

forms/basicforms/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'basic_app:user_login' %}"enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Register">
    </form>
</div>
{% endblock %}

forms/basicforms/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
    <h1>Welcome to other</h1>
    <h2>Example of template inheritance</h2>
{% endblock %}

forms/basicforms/templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Tahnk you for registering!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
</div>
{% endblock %}

forms/basicforms/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Link to index</a>
  </body>
</html>